#### Name: Hira Arif

#### Email : Hiraarif077@gmail.com

### Pandas Practice

### Install Library

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\home\appdata\local\programs\python\python312\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in c:\users\home\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\home\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\home\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\home\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\home\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\home\appdata\local\programs\python\python312\lib\site-packages (3.1.5)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: et-xmlfile in c:\users\home\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)

### Import Library

In [4]:
import pandas as pd

### Create the Data Frame from Excel File

In [5]:
dataset2=pd.read_excel("New Excel File.xlsx")
print("DATAFRAME")
dataset2

DATAFRAME

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
0,Huma,Huma123@gmail.com,Rawalpindi,MS,2,25k,40k
1,Aliya,Aliya677@gmail.com,Lahore,Bsc,4,20k,45k
2,Sara,Sara698@gmmail.com,Jehlum,BS,2,22k,58k
3,Sana,Sana023@gmail.com,KPK,Fsc,3,20k,52k
4,Mahnoor,Mahnoor741@gmail.com,Islamabad,BS,1,22k,40k
5,Hafsa,Hafsa895@gmail.com,Rawalpindi,MS,1,20k,60k
6,Aatka,Aatka112@gmail.com,Kpk,Mphil,0,21k,40k
7,Shahida,Shahida013@gmail.com,Sindh,BS,4,20k,30k
8,Summiya,Summiya113@gmail.com,Islamabd,BS,5,18k,43k
9,Riffat,Riffat568@gmail.com,Rawalpindi,BS,2,13k,50k

### Using Different Functions

### 1. Info Function

In [5]:
dataset2.info

<bound method DataFrame.info of   School Tecaher                   Email      Address Qualification   \
0            Huma      Huma123@gmail.com   Rawalpindi             MS
1          Aliya      Aliya677@gmail.com       Lahore            Bsc
2            Sara     Sara698@gmmail.com       Jehlum             BS
3           Sana       Sana023@gmail.com          KPK            Fsc
4        Mahnoor    Mahnoor741@gmail.com    Islamabad             BS
5          Hafsa      Hafsa895@gmail.com  Rawalpindi              MS
6           Aatka     Aatka112@gmail.com          Kpk          Mphil
7         Shahida   Shahida013@gmail.com        Sindh             BS
8        Summiya   Summiya113@gmail.com      Islamabd             BS
9         Riffat     Riffat568@gmail.com   Rawalpindi             BS

   Experience Previous Salary  Demand Salary
0           2              25k            40k
1           4              20k            45k
2           2              22k            58k
3           3              20k            52k
4           1              22k            40k
5           1              20k            60k
6           0              21k            40k
7           4              20k            30k
8           5              18k            43k
9           2              13k            50k  >

### 2. Describe Function

In [6]:
dataset2.describe

<bound method NDFrame.describe of   School Tecaher                   Email      Address Qualification   \
0            Huma      Huma123@gmail.com   Rawalpindi             MS
1          Aliya      Aliya677@gmail.com       Lahore            Bsc
2            Sara     Sara698@gmmail.com       Jehlum             BS
3           Sana       Sana023@gmail.com          KPK            Fsc
4        Mahnoor    Mahnoor741@gmail.com    Islamabad             BS
5          Hafsa      Hafsa895@gmail.com  Rawalpindi              MS
6           Aatka     Aatka112@gmail.com          Kpk          Mphil
7         Shahida   Shahida013@gmail.com        Sindh             BS
8        Summiya   Summiya113@gmail.com      Islamabd             BS
9         Riffat     Riffat568@gmail.com   Rawalpindi             BS

   Experience Previous Salary  Demand Salary
0           2              25k            40k
1           4              20k            45k
2           2              22k            58k
3           3              20k            52k
4           1              22k            40k
5           1              20k            60k
6           0              21k            40k
7           4              20k            30k
8           5              18k            43k
9           2              13k            50k  >

### 3. Data type  Function

In [7]:
dataset2.dtypes

School Tecaher      object
Email               object
Address             object
Qualification       object
Experience           int64
Previous Salary     object
Demand Salary       object
dtype: object

### 4. Slicing Function

In [11]:
dataset2[2:6]

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
2,Sara,Sara698@gmmail.com,Jehlum,BS,2,22k,58k
3,Sana,Sana023@gmail.com,KPK,Fsc,3,20k,52k
4,Mahnoor,Mahnoor741@gmail.com,Islamabad,BS,1,22k,40k
5,Hafsa,Hafsa895@gmail.com,Rawalpindi,MS,1,20k,60k

### 5. Sorting by Column Function

In [73]:
dataset2.sort_values(by = "Address")

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
4,Mahnoor,Mahnoor741@gmail.com,Islamabad,BS,1,22k,40k
8,Summiya,Summiya113@gmail.com,Islamabd,BS,5,18k,43k
2,Sara,Sara698@gmmail.com,Jehlum,BS,2,22k,58k
3,Sana,Sana023@gmail.com,KPK,Fsc,3,20k,52k
6,Aatka,Aatka112@gmail.com,Kpk,Mphil,0,21k,40k
1,Aliya,Aliya677@gmail.com,Lahore,Bsc,4,20k,45k
0,Huma,Huma123@gmail.com,Rawalpindi,MS,2,25k,40k
9,Riffat,Riffat568@gmail.com,Rawalpindi,BS,2,13k,50k
5,Hafsa,Hafsa895@gmail.com,Rawalpindi,MS,1,20k,60k
7,Shahida,Shahida013@gmail.com,Sindh,BS,4,20k,30k

### 6. Sorting by Index Function

In [74]:
dataset2.sort_index(axis = 1, ascending = True)

,Address,Demand Salary,Email,Experience,Previous Salary,Qualification,School Tecaher
0,Rawalpindi,40k,Huma123@gmail.com,2,25k,MS,Huma
1,Lahore,45k,Aliya677@gmail.com,4,20k,Bsc,Aliya
2,Jehlum,58k,Sara698@gmmail.com,2,22k,BS,Sara
3,KPK,52k,Sana023@gmail.com,3,20k,Fsc,Sana
4,Islamabad,40k,Mahnoor741@gmail.com,1,22k,BS,Mahnoor
5,Rawalpindi,60k,Hafsa895@gmail.com,1,20k,MS,Hafsa
6,Kpk,40k,Aatka112@gmail.com,0,21k,Mphil,Aatka
7,Sindh,30k,Shahida013@gmail.com,4,20k,BS,Shahida
8,Islamabd,43k,Summiya113@gmail.com,5,18k,BS,Summiya
9,Rawalpindi,50k,Riffat568@gmail.com,2,13k,BS,Riffat

### 7. Head Function

In [78]:
dataset2.head()

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
0,Huma,Huma123@gmail.com,Rawalpindi,MS,2,25k,40k
1,Aliya,Aliya677@gmail.com,Lahore,Bsc,4,20k,45k
2,Sara,Sara698@gmmail.com,Jehlum,BS,2,22k,58k
3,Sana,Sana023@gmail.com,KPK,Fsc,3,20k,52k
4,Mahnoor,Mahnoor741@gmail.com,Islamabad,BS,1,22k,40k

In [81]:
dataset2.head(3)

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
0,Huma,Huma123@gmail.com,Rawalpindi,MS,2,25k,40k
1,Aliya,Aliya677@gmail.com,Lahore,Bsc,4,20k,45k
2,Sara,Sara698@gmmail.com,Jehlum,BS,2,22k,58k

### 8. Tail Function

In [82]:
dataset2.tail()

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
5,Hafsa,Hafsa895@gmail.com,Rawalpindi,MS,1,20k,60k
6,Aatka,Aatka112@gmail.com,Kpk,Mphil,0,21k,40k
7,Shahida,Shahida013@gmail.com,Sindh,BS,4,20k,30k
8,Summiya,Summiya113@gmail.com,Islamabd,BS,5,18k,43k
9,Riffat,Riffat568@gmail.com,Rawalpindi,BS,2,13k,50k

In [83]:
dataset2.tail(8)

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
2,Sara,Sara698@gmmail.com,Jehlum,BS,2,22k,58k
3,Sana,Sana023@gmail.com,KPK,Fsc,3,20k,52k
4,Mahnoor,Mahnoor741@gmail.com,Islamabad,BS,1,22k,40k
5,Hafsa,Hafsa895@gmail.com,Rawalpindi,MS,1,20k,60k
6,Aatka,Aatka112@gmail.com,Kpk,Mphil,0,21k,40k
7,Shahida,Shahida013@gmail.com,Sindh,BS,4,20k,30k
8,Summiya,Summiya113@gmail.com,Islamabd,BS,5,18k,43k
9,Riffat,Riffat568@gmail.com,Rawalpindi,BS,2,13k,50k

### 9. Shape Function

In [92]:
dataset2.shape

(10, 7)

### 10. Index Function

In [94]:
dataset2.index

RangeIndex(start=0, stop=10, step=1)

### 11. Column Function

In [1]:
dataset2.columns

NameError: name 'dataset2' is not defined

### 12. Location Function

In [147]:
dataset2.loc[:, ["Email", "Address"]]

                   Email      Address
0      Huma123@gmail.com   Rawalpindi
1     Aliya677@gmail.com       Lahore
2     Sara698@gmmail.com       Jehlum
3      Sana023@gmail.com          KPK
4   Mahnoor741@gmail.com    Islamabad
5     Hafsa895@gmail.com  Rawalpindi
6     Aatka112@gmail.com          Kpk
7   Shahida013@gmail.com        Sindh
8  Summiya113@gmail.com      Islamabd
9    Riffat568@gmail.com   Rawalpindi

In [113]:
dataset2.iloc[5,1]

'Hafsa895@gmail.com'

In [132]:
dataset2.loc[1:2]

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
1,Aliya,Aliya677@gmail.com,Lahore,Bsc,4,20k,45k
2,Sara,Sara698@gmmail.com,Jehlum,BS,2,22k,58k

In [122]:
dataset2.loc["2":"5"]

,School Tecaher,Email,Address,Qualification,Experience,Previous Salary,Demand Salary
2,Sara,Sara698@gmmail.com,Jehlum,BS,2,22k,58k
3,Sana,Sana023@gmail.com,KPK,Fsc,3,20k,52k
4,Mahnoor,Mahnoor741@gmail.com,Islamabad,BS,1,22k,40k
5,Hafsa,Hafsa895@gmail.com,Rawalpindi,MS,1,20k,60k

In [123]:
dataset2.loc[2]

School Tecaher                    Sara
Email               Sara698@gmmail.com
Address                         Jehlum
Qualification                       BS
Experience                           2
Previous Salary                    22k
Demand Salary                      58k
Name: 2, dtype: object

In [133]:
dataset2.Email

0        Huma123@gmail.com
1       Aliya677@gmail.com
2       Sara698@gmmail.com
3        Sana023@gmail.com
4     Mahnoor741@gmail.com
5       Hafsa895@gmail.com
6       Aatka112@gmail.com
7     Shahida013@gmail.com
8    Summiya113@gmail.com
9      Riffat568@gmail.com
Name: Email, dtype: object

### 13. Transpose Function

In [144]:
dataset2.T

,0,1,2,3,4,5,6,7,8,9
School Tecaher,Huma,Aliya,Sara,Sana,Mahnoor,Hafsa,Aatka,Shahida,Summiya,Riffat
Email,Huma123@gmail.com,Aliya677@gmail.com,Sara698@gmmail.com,Sana023@gmail.com,Mahnoor741@gmail.com,Hafsa895@gmail.com,Aatka112@gmail.com,Shahida013@gmail.com,Summiya113@gmail.com,Riffat568@gmail.com
Address,Rawalpindi,Lahore,Jehlum,KPK,Islamabad,Rawalpindi,Kpk,Sindh,Islamabd,Rawalpindi
Qualification,MS,Bsc,BS,Fsc,BS,MS,Mphil,BS,BS,BS
Experience,2,4,2,3,1,1,0,4,5,2
Previous Salary,25k,20k,22k,20k,22k,20k,21k,20k,18k,13k
Demand Salary,40k,45k,58k,52k,40k,60k,40k,30k,43k,50k